//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JdRunner
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductExclusion.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to barcode.
        /// </summary>
        public static string barcode
        {
            get
            {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BARCODE.
        /// </summary>
        public static string BARCODE2
        {
            get
            {
                return ResourceManager.GetString("BARCODE2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CLASS.
        /// </summary>
        public static string CLASS
        {
            get
            {
                return ResourceManager.GetString("CLASS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to classDesc.
        /// </summary>
        public static string classDesc
        {
            get
            {
                return ResourceManager.GetString("classDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to classDescription.
        /// </summary>
        public static string classDescription
        {
            get
            {
                return ResourceManager.GetString("classDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COLOR.
        /// </summary>
        public static string color
        {
            get
            {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COLOR.
        /// </summary>
        public static string COLOR2
        {
            get
            {
                return ResourceManager.GetString("COLOR2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to colorDesc.
        /// </summary>
        public static string colorDesc
        {
            get
            {
                return ResourceManager.GetString("colorDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COLORDESC.
        /// </summary>
        public static string COLORDESC2
        {
            get
            {
                return ResourceManager.GetString("COLORDESC2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to colorDescription.
        /// </summary>
        public static string colorDescription
        {
            get
            {
                return ResourceManager.GetString("colorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to createdBy.
        /// </summary>
        public static string createdBy
        {
            get
            {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to createdDate.
        /// </summary>
        public static string createdDate
        {
            get
            {
                return ResourceManager.GetString("createdDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to departmentDesc.
        /// </summary>
        public static string departmentDesc
        {
            get
            {
                return ResourceManager.GetString("departmentDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to departmentDescription.
        /// </summary>
        public static string departmentDescription
        {
            get
            {
                return ResourceManager.GetString("departmentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DEPT.
        /// </summary>
        public static string DEPT
        {
            get
            {
                return ResourceManager.GetString("DEPT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description
        {
            get
            {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DIMENSION.
        /// </summary>
        public static string dimension
        {
            get
            {
                return ResourceManager.GetString("dimension", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DIMENSION.
        /// </summary>
        public static string DIMENSION2
        {
            get
            {
                return ResourceManager.GetString("DIMENSION2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dimensionDesc.
        /// </summary>
        public static string dimensionDesc
        {
            get
            {
                return ResourceManager.GetString("dimensionDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dimensionDescription.
        /// </summary>
        public static string dimensionDescription
        {
            get
            {
                return ResourceManager.GetString("dimensionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to discounts.
        /// </summary>
        public static string discounts
        {
            get
            {
                return ResourceManager.GetString("discounts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to earnLoyalty.
        /// </summary>
        public static string earnLoyalty
        {
            get
            {
                return ResourceManager.GetString("earnLoyalty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to fkmdselevelno.
        /// </summary>
        public static string fkmdselevelno
        {
            get
            {
                return ResourceManager.GetString("fkmdselevelno", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to fkparentmdseno.
        /// </summary>
        public static string fkparentmdseno
        {
            get
            {
                return ResourceManager.GetString("fkparentmdseno", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mdse_description.
        /// </summary>
        public static string mdse_description
        {
            get
            {
                return ResourceManager.GetString("mdse_description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to modifiedBy.
        /// </summary>
        public static string modifiedBy
        {
            get
            {
                return ResourceManager.GetString("modifiedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to modifiedDate.
        /// </summary>
        public static string modifiedDate
        {
            get
            {
                return ResourceManager.GetString("modifiedDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to pkmerchandiseno.
        /// </summary>
        public static string pkmerchandiseno
        {
            get
            {
                return ResourceManager.GetString("pkmerchandiseno", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to pkstyleno.
        /// </summary>
        public static string pkstyleno
        {
            get
            {
                return ResourceManager.GetString("pkstyleno", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PKSTYLENO.
        /// </summary>
        public static string PKSTYLENO2
        {
            get
            {
                return ResourceManager.GetString("PKSTYLENO2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PRODUCTNO.
        /// </summary>
        public static string PRODUCTNO
        {
            get
            {
                return ResourceManager.GetString("PRODUCTNO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to promotions.
        /// </summary>
        public static string promotions
        {
            get
            {
                return ResourceManager.GetString("promotions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to redeemLoyalty.
        /// </summary>
        public static string redeemLoyalty
        {
            get
            {
                return ResourceManager.GetString("redeemLoyalty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sizeDesc.
        /// </summary>
        public static string sizeDesc
        {
            get
            {
                return ResourceManager.GetString("sizeDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sizeDescription.
        /// </summary>
        public static string sizeDescription
        {
            get
            {
                return ResourceManager.GetString("sizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        public static string SKU
        {
            get
            {
                return ResourceManager.GetString("SKU", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SKUDIMENSION.
        /// </summary>
        public static string SKUDIMENSION
        {
            get
            {
                return ResourceManager.GetString("SKUDIMENSION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SKUSIZE.
        /// </summary>
        public static string SKUSIZE
        {
            get
            {
                return ResourceManager.GetString("SKUSIZE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to styleDesc.
        /// </summary>
        public static string styleDesc
        {
            get
            {
                return ResourceManager.GetString("styleDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to STYLEDESC.
        /// </summary>
        public static string STYLEDESC2
        {
            get
            {
                return ResourceManager.GetString("STYLEDESC2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to styleDescription.
        /// </summary>
        public static string styleDescription
        {
            get
            {
                return ResourceManager.GetString("styleDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to styleno.
        /// </summary>
        public static string styleno
        {
            get
            {
                return ResourceManager.GetString("styleno", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to STYLENO.
        /// </summary>
        public static string STYLENO2
        {
            get
            {
                return ResourceManager.GetString("STYLENO2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUBCLASS.
        /// </summary>
        public static string SUBCLASS
        {
            get
            {
                return ResourceManager.GetString("SUBCLASS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to subclassDesc.
        /// </summary>
        public static string subclassDesc
        {
            get
            {
                return ResourceManager.GetString("subclassDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to subClassDescription.
        /// </summary>
        public static string subClassDescription
        {
            get
            {
                return ResourceManager.GetString("subClassDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to uniqueClass.
        /// </summary>
        public static string uniqueClass
        {
            get
            {
                return ResourceManager.GetString("uniqueClass", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to uniqueDepartment.
        /// </summary>
        public static string uniqueDepartment
        {
            get
            {
                return ResourceManager.GetString("uniqueDepartment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to uniqueExcludeGroup.
        /// </summary>
        public static string uniqueExcludeGroup
        {
            get
            {
                return ResourceManager.GetString("uniqueExcludeGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to uniqueSku.
        /// </summary>
        public static string uniqueSku
        {
            get
            {
                return ResourceManager.GetString("uniqueSku", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to uniqueStyleNo.
        /// </summary>
        public static string uniqueStyleNo
        {
            get
            {
                return ResourceManager.GetString("uniqueStyleNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to uniqueSubclass.
        /// </summary>
        public static string uniqueSubclass
        {
            get
            {
                return ResourceManager.GetString("uniqueSubclass", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VENDOR.
        /// </summary>
        public static string VENDOR
        {
            get
            {
                return ResourceManager.GetString("VENDOR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to vendorStyleNo.
        /// </summary>
        public static string vendorStyleNo
        {
            get
            {
                return ResourceManager.GetString("vendorStyleNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VENDORSTYLENO.
        /// </summary>
        public static string VENDORSTYLENO2
        {
            get
            {
                return ResourceManager.GetString("VENDORSTYLENO2", resourceCulture);
            }
        }
    }
}
